<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [2]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Train the Decision Tree model

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

#Predict test set result

In [14]:
y_pred = classifier.predict(X_test)

#Stats

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 0  1  1  0  0  0]
 [ 0  2  5  3  1  0]
 [ 2  7 78 46  2  0]
 [ 0  4 31 85 16  6]
 [ 0  0  1 16  9  1]
 [ 0  0  0  1  2  0]]
0.54375
