<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [4]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Train the KNN

In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=21)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

#Predict test set result

In [8]:
y_pred = classifier.predict(X_test)

#Stats

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[ 0  0  1  1  0  0]
 [ 0  0  9  2  0  0]
 [ 0  0 97 35  3  0]
 [ 0  0 47 82 13  0]
 [ 0  0  2 12 13  0]
 [ 0  0  0  1  2  0]]
0.6
