<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [3]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[5:7] = sc.fit_transform(X_train[5:7])
X_test[5:7] = sc.fit_transform(X_test[5:7])

#Train the KNN

In [44]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=21)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

#Predict test set result

In [45]:
y_pred = classifier.predict(X_test)

#Stats

In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   1   1   0   0]
 [  0   0  10   1   0   0]
 [  0   0 102  32   1   0]
 [  0   0  61  75   6   0]
 [  0   0   4  17   6   0]
 [  0   0   0   1   2   0]]
0.571875
