<a href="https://colab.research.google.com/github/nickync/ML/blob/Classification/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [4]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling (column5,6)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[5:7] = sc.fit_transform(X_train[5:7])
X_test[5:7] = sc.fit_transform(X_test[5:7])

[[10.8    0.47   0.43  ...  3.17   0.76  10.8  ]
 [ 8.1    0.82   0.    ...  3.36   0.53   9.6  ]
 [ 9.1    0.29   0.33  ...  3.26   0.84  11.7  ]
 ...
 [ 9.1    0.34   0.42  ...  3.18   0.55  11.4  ]
 [ 9.1    0.765  0.04  ...  3.29   0.54   9.7  ]
 [ 8.2    0.32   0.42  ...  3.27   0.55  12.3  ]]


#Train the Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=40000)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=40000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#Predict the test set results

In [19]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1)),1))

#Stats

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, hinge_loss, mean_squared_log_error
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy_score:{}'.format(accuracy_score(y_test, y_pred)))
print('MSLE: {}'.format(mean_squared_log_error(y_test, y_pred)))


[[  0   0   2   0   0   0]
 [  0   0   6   4   1   0]
 [  0   0 101  33   1   0]
 [  0   0  38  93  11   0]
 [  0   0   2  16   9   0]
 [  0   0   0   1   2   0]]
Accuracy_score:0.634375
MSLE: 0.011592986879913572
