<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [2]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Train the Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=3000)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=3000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#Predict the test set results

In [6]:
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1)),1))

#Stats

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, hinge_loss, mean_squared_log_error
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy_score:{}'.format(accuracy_score(y_test, y_pred)))
print('MSLE: {}'.format(mean_squared_log_error(y_test, y_pred)))


[[  0   0   2   0   0   0]
 [  0   0   6   4   1   0]
 [  0   0 106  28   1   0]
 [  0   0  44  77  21   0]
 [  0   0   2  16   9   0]
 [  0   0   0   1   2   0]]
Accuracy_score:0.6
MSLE: 0.012224451755706228
