<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/Naive%20Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [2]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Train the Gaussian Naive Bayes

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

#Predict test set result

In [10]:
y_pred = classifier.predict(X_test)

#Stats

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   2   0   0   0]
 [  0   0  10   0   1   0]
 [  2   3 121   1   8   0]
 [  0   2 105   0  26   9]
 [  1   0  10   0   9   7]
 [  0   0   0   0   3   0]]
0.40625
