<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Classification/Support%20Vector%20Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [2]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

#Train the SVM (rbf kernel)

In [5]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Predict test set result

In [6]:
y_pred = classifier.predict(X_test)

#Stats

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   1   1   0   0]
 [  0   0   8   3   0   0]
 [  0   0 102  32   1   0]
 [  0   0  40  96   6   0]
 [  0   0   1  17   9   0]
 [  0   0   0   1   2   0]]
0.646875


#Train the SVM ('linear' kernel)

In [8]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Predict test set result

In [9]:
y_pred = classifier.predict(X_test)

#Stats

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   2   0   0   0]
 [  0   0   6   4   1   0]
 [  0   0 105  29   1   0]
 [  0   0  48  74  20   0]
 [  0   0   2  18   7   0]
 [  0   0   0   1   2   0]]
0.58125
