<a href="https://colab.research.google.com/github/nickync/Machine-Learning/blob/Regression/Support%20Vector%20Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Load dataset

In [3]:
dataset = pd.read_csv('winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

#Splitting the dataset

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size = 0.2, random_state = 0)

#Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[5:7] = sc.fit_transform(X_train[5:7])
X_test[5:7] = sc.fit_transform(X_test[5:7])

#Train the SVM (rbf kernel)

In [6]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Predict test set result

In [7]:
y_pred = classifier.predict(X_test)

#Stats

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   0   2   0   0]
 [  0   0   3   8   0   0]
 [  0   0  52  83   0   0]
 [  0   0  32 110   0   0]
 [  0   0   1  26   0   0]
 [  0   0   0   3   0   0]]
0.50625


#Train the SVM ('linear' kernel)

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Predict test set result

In [10]:
y_pred = classifier.predict(X_test)

#Stats

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn import metrics
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   2   0   0   0]
 [  0   0   7   4   0   0]
 [  0   0 105  30   0   0]
 [  0   0  45  97   0   0]
 [  0   0   2  25   0   0]
 [  0   0   0   3   0   0]]
0.63125
